version: '3'
services:
  mlflow_service:
    image: ghcr.io/mlflow/mlflow:v2.13.1
    ports:
      - "5001:5000"  
    command: mlflow server --host 0.0.0.0        

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
